### ISSUE TITLE
HA on/off switch not working

### ISSUE THREAD

**Issue by Boosmoo** [brefra/home-assistant-plugwise-stick#8]
Hello brefra

I tried your integration in HA for the Plugwise circle and circle+ but cant use the on/off switches in HA(they bounce back). I can see the power and kWh etc. What should I do?

Yours faithfully,
Boosmoo

**Comment by brefra** [comment]
Hi Boosmoo, the "bounce back" is probably due to something like a communication issue. In the end the Circle(+) device should acknowledge the switch request, which wil trigger HA to show the proper switch state.
I do know sometimes it could take up to 10 seconds to have HA report the correct relay state (while in the meantime it kind of bounces back). Doesn't switch the relay at all?

**Comment by Boosmoo** [comment]
Hi Brefra, it maybe switched on time from on to off and cant turn it back on

**Comment by Boosmoo** [comment]
@brefra you have to excuse me they do work but just really slow. Thank you for answering my question.
